development:
  APP_PERMISSIONS: 'email,user_birthday,user_location,user_likes'

test:
  APP_PERMISSIONS: 'email,user_birthday,user_location,user_likes'

production:
  APP_PERMISSIONS: 'email,user_birthday,user_location,user_likes'
